### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by jerone** [agiove/clarity-vscode#1]
Interesting extension. Any plans to update this to the latest Clarity version?

**Comment by agiove** [comment]
I abandoned clarity use 4 years ago. Without any help I think the extension won’t be updated. Thanks for your interest btw

**Comment by jerone** [comment]
I was already looking at the source. The snippets are clear, but I'm missing some documentation about what the `src` folder contains. Especially the [`src/metadata`](https://github.com/agiove/clarity-vscode/tree/master/src/metadata) folder. Where is used for and how did you generate it?

**Comment by agiove** [comment]
Metadata comes from clarity itself, you can find it in the npm modules folder. The goal should be to use what’s already there in npm with no manipulation

**Comment by jerone** [comment]
I've been working slowing at updating this extension; SDK, NPM packages and code cleanup.
Also trying to find a reliability way to include the metadata.

All changes are pushed to a separate branch: https://github.com/agiove/clarity-vscode/compare/master...jerone:feature/update?w=1

Once the code at an acceptable level, I'll try to send a PR.
Are you interested in reviewing it and possibly merge it?

**Comment by agiove** [comment]
Sure I am. I saw your current wip. If you need something from my side or wanna share your roadmap feel free to start a chat
